# Generated by Django 4.1.7 on 2023-04-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
    ]
